# Generated by Django 3.2.16 on 2022-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_of_cores', models.PositiveSmallIntegerField()),
                ('processor_technology', models.PositiveSmallIntegerField()),
                ('base_clock', models.PositiveSmallIntegerField()),
                ('thermal_design_power', models.PositiveSmallIntegerField()),
                ('cache_mamory', models.TextField()),
                ('integrated_graphics_core', models.TextField()),
            ],
        ),
    ]
