# Generated by Django 3.2.16 on 2022-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221109_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorcharacteristics',
            name='units_in_stock',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
