# Generated by Django 3.2.16 on 2022-11-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_processorcharacteristics_units_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorcharacteristics',
            name='price',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
